### ISSUE TITLE
 Invalid usage: This command requires exactly 1 cask argument.

### ISSUE THREAD

**Issue by 1zilc** [EINDEX/bump-homebrew-cask-action#1]
Thanks for your work, I'm having a problem using it, I don't know where I'm going wrong
```yml
name: Release

on:
  release:
    types: [published]

jobs:
  broadcast_release:
    runs-on: macOS-latest

    steps:
      - name: Homebrew Cask Bumper
        uses: EINDEX/bump-homebrew-cask-action@v1.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          package: 'fishing-funds'
```
The [error log](https://github.com/1zilc/fishing-funds/runs/5225861297?check_suite_focus=true)
